services:
  db:
    image: postgres:14
    container_name: outbreak_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outbreak_db_user -d outbreak_db || exit 0"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: outbreak_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 43200  # 12 hours
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  backend-app:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /code
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      ENV: dev
      DEBUG: "true"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data:
  pgadmin_data:
